#include "DualArmControl.h"

void DualArmControl::filtering(){
       // =====================================================================================
       // 4. ALPHA-BETA FILTER (Kalman-like tracking for Position and Velocity)
       // -------------------------------------------------------------------------------------
       // This steady-state filter smooths the noisy force measurement (lambdaMeasured_)
       // and estimates its first derivative (lambdaDotFiltered_) without a severe lag.
       // Tuning Guide:
       // - alpha_k (0 to 1): Controls position tracking. Higher = faster response but noisy.
       //                                                 Lower  = smoother but introduces lag.
       // - beta_k  (0 to 1): Controls velocity tracking. Higher = reactive but shaky derivative.
       // =====================================================================================
       smoothFilter_.alpha =   0.10;        smoothFilter_.beta  =   0.005;
       balancedFilter_.alpha = 0.25;        balancedFilter_.beta  = 0.02;
       fastFilter_.alpha =     0.45;        fastFilter_.beta  =     0.10;   

       smoothFilter_.update(lambdaMeasured_, timeStep);
       balancedFilter_.update(lambdaMeasured_, timeStep);
       fastFilter_.update(lambdaMeasured_, timeStep);
       // =====================================================================================
       // 4.1 FIRST-ORDER LOW-PASS FILTER (for comparison only)
       // -------------------------------------------------------------------------------------
       // Classical first-order low-pass filter:
       // y(k) = y(k-1) + alpha * (x(k) - y(k-1))
       // Smaller alpha -> stronger smoothing           Larger alpha  -> faster response
       // =====================================================================================
       lowPass(lambdaFiltered_lowpass_moltosmooth, lambdaMeasured_, 0.05);
       lowPass(lambdaFiltered_lowpass_smooth,      lambdaMeasured_, 0.20);
       lowPass(lambdaFiltered_lowpass_mid,         lambdaMeasured_, 0.30);
       lowPass(lambdaFiltered_lowpass_high,        lambdaMeasured_, 0.70);
       double tau = 1.0 / (2.0 * M_PI * gains.cutoffPeriod);
       double alpha_lpcut = timeStep / (tau + timeStep);
       lowPass(lambdaFiltered_lowpass_cut, lambdaMeasured_, alpha_lpcut);
}






void DualArmControl::currentInternalForce(){
       // Rotation Matrix
              auto RL = robots().robot(leftRobotIndex_).bodyPosW(eeName_).rotation();
              auto RR = robots().robot(rightRobotIndex_).bodyPosW(eeName_).rotation();
       // World Frame FORCES
              Eigen::Matrix<double, 6, 1> fL_world;
              Eigen::Matrix<double, 6, 1> fR_world;
              Eigen::Matrix<double, 12, 1> f_meas;
       // Contact Force Measure
              sva::ForceVecd WL = leftImpedanceTask_->measuredWrench();
              sva::ForceVecd WR = rightImpedanceTask_->measuredWrench();
              
              fL_world.head<3>() = RL * WL.couple();
              fL_world.tail<3>() = RL * WL.force();
              fR_world.head<3>() = RR * WR.couple();
              fR_world.tail<3>() = RR * WR.force();
       // Group into one vector
              f_meas.segment<6>(0) = fL_world;
              f_meas.segment<6>(6) = fR_world;
       // Null-Space Projection Matrix
              Eigen::Matrix<double, 12, 12> Pint = Eigen::Matrix<double, 12, 12>::Identity() - Gpinv_ * G_;
              Eigen::Matrix<double, 12, 1> internalForce = Pint * f_meas;

              n_s << 0, 0, 0, 0, 1, 0,  //  Squeeze direction
                     0, 0, 0, 0, -1, 0;
       // Null Space projection of squeeze
              Eigen::JacobiSVD<Eigen::MatrixXd> svd(G_, Eigen::ComputeFullV);
              int rank = svd.rank();
              Eigen::MatrixXd N = svd.matrixV().rightCols(G_.cols() - rank);
              n_squeeze = N * (N.transpose() * n_s);
              n_squeeze.stableNormalize();
       lambdaMeasured_ = n_squeeze.transpose() * internalForce;
       filtering();
}

void DualArmControl::updateContactForces(){
       sva::ForceVecd target_{Eigen::Vector3d::Zero(), Eigen::Vector3d(0.0, 0.0, -gains.lambda_desired)};
              
       currentInternalForce();

       // =====================================================================================
       // 5. INTERNAL SQUEEZE FORCE CONTROL
       
       meas = lambdaFiltered_lowpass_cut;
       error_internalForce = gains.lambda_desired - meas;
              
       double Ki = 2.0;                                                  // Integral gain [N/(N*s)]
       double maxRate = 15.0;                                            // Maximum change of reference [N/s]
       double delta = Ki * error_internalForce * timeStep;               // Increment generated by the error
       delta = std::clamp(delta,-maxRate * timeStep,maxRate * timeStep); // Limit how fast the reference is allowed to change

       lambdaCommand_ += delta;                                       // Update the reference
       lambdaCommand_ = std::clamp(lambdaCommand_, -80.0, 80.0);      // Safety limits

       // =====================================================================================
       // 6. PROIETTA NEL WRENCH

       Eigen::Matrix<double, 12, 1> f_input = n_squeeze * lambdaCommand_;
       Eigen::Matrix<double, 6, 1> wL_world = f_input.segment<6>(0);
       Eigen::Matrix<double, 6, 1> wR_world = f_input.segment<6>(6);

       Eigen::Matrix<double, 6, 1> wL_local;
       Eigen::Matrix<double, 6, 1> wR_local;
       // Ricalcoliamo le rotazioni qui per trasformare i comandi in locali
       auto RL = robots().robot(leftRobotIndex_).bodyPosW(eeName_).rotation();
       auto RR = robots().robot(rightRobotIndex_).bodyPosW(eeName_).rotation();

       wL_local.head<3>() = RL.transpose() * wL_world.head<3>();
       wL_local.tail<3>() = RL.transpose() * wL_world.tail<3>();

       wR_local.head<3>() = RR.transpose() * wR_world.head<3>();
       wR_local.tail<3>() = RR.transpose() * wR_world.tail<3>();

       cmdLeft.couple() = wL_local.head<3>();
       cmdLeft.force()  = wL_local.tail<3>();

       cmdRight.couple() = wR_local.head<3>();
       cmdRight.force()  = wR_local.tail<3>();

       // =====================================================================================
       // 7. SEND WRENCHES
       leftImpedanceTask_->targetWrench(cmdLeft);
       rightImpedanceTask_->targetWrench(cmdRight);     
}






// theorical peak 10/sqrt3 ≈ 5.7735.pre gain
double DualArmControl::DemandForces(double K) const{
    const double t2 = t_norm * t_norm;
    const double t3 = t2 * t_norm;
    const double t4 = t3 * t_norm;
    //return K * std::abs(60.0 * t_norm - 180.0 * t2 + 120.0 * t3);
    return K * std::abs(30.0 * t2 - 60.0 * t3 + 30.0 * t4);
}

void DualArmControl::CoulombForces(double mu){
       // force measure
       sva::ForceVecd WL = leftImpedanceTask_->measuredWrench();
       sva::ForceVecd WR = rightImpedanceTask_->measuredWrench();
       Eigen::Vector3d FL = WL.force();
       Eigen::Vector3d FR = WR.force();

       double FnL = FL.z();
       double FnR = FR.z();

       double FtL = FL.head<2>().norm();   // sqrt(Fx² + Fy²)
       double FtR = FR.head<2>().norm();

       

       bool leftOK  = (FnL >= FtL/mu);
       bool rightOK = (FnR >= FtR/mu);

}


